---
dependency:
  name: galaxy
  enabled: false
driver:
  name: lxd
lint: |
  set -e
  ansible-lint
platforms:
  - name: instance
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"
provisioner:
  name: ansible
verifier:
  name: ansible
